package com.knowledgeVista.Migration.sheduler;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.time.LocalDate;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import com.knowledgeVista.Email.EmailService;
import com.knowledgeVista.Migration.BackupService;
import com.knowledgeVista.Migration.model.BackupScheduleConfig;
import com.knowledgeVista.Migration.repo.BackupSheduleConfigRepo;
import com.knowledgeVista.User.Repository.MuserRepositories;

@Service
public class BackupSchedulerService {

	@Autowired
	private BackupSheduleConfigRepo configRepo;
	@Autowired
	private EmailService emailService;
	@Autowired
	private BackupService backupService;
	@Value("${backend.domain}")
	private String backendDomain;

	@Value("${developer.mail}")
	private String devmail;
	@Autowired
	private MuserRepositories muserRepo;

	@Scheduled(cron = "0 0 2 * * *") // Runs daily at 2 AM
	public void executeScheduledBackups() {
		List<BackupScheduleConfig> configs = configRepo.findAll();
		LocalDate today = LocalDate.now();
		for (BackupScheduleConfig config : configs) {
			if (shouldBackupToday(config, today)) {
				try {
					backupService.performBackupAndUpload(config.getInstitutionName(), config.getMaxBackupsToKeep());
				} catch (Exception e) {
					List<String> adminemails = muserRepo.findAdminEmailfromInstitutionName(config.getInstitutionName());
					handleBackupFailure(e, adminemails, List.of(devmail));
				}
			}
		}
	}

	@Scheduled(cron = "0 0 2 * * *") // Runs daily at 2 AM
	public void executedailyBackups() {
		try {
			backupService.backupDatabaseToFolder();
		} catch (Exception e) {
			handleBackupFailure(e, List.of(devmail), List.of());
		}
	}

	public void handleBackupFailure(Exception e, List<String> developerMails, List<String> adminMails) {
		String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());
		String subject = "🚨 Database Backup Failure Alert";

		try {
			// Developer Email Body (detailed)
			String devBody = "<h2 style='color: #d9534f;'>Database Backup Failed</h2>"
					+ "<p><strong>Timestamp:</strong> " + timestamp + "</p>" + "<p><strong>Backend Server:</strong> "
					+ backendDomain + "</p>" + "<p><strong>Exception Details:</strong></p>"
					+ "<pre style='background-color: #f8f9fa; color: #212529; padding: 12px; border-radius: 5px; border: 1px solid #dee2e6;'>"
					+ "<p><strong>Issue:</strong> " + (e.getMessage() != null ? e.getMessage() : "Unknown error")
					+ "</p>" + "<p><strong>Cause:</strong> " + (e.getCause() != null ? e.getCause().toString() : "N/A")
					+ "</p>" + "<p><strong>StackTrace:</strong> " + getStackTraceAsString(e) + "</pre>"
					+ "<p>Please investigate the root cause. This is a system-generated alert.</p>";

			// Admin Email Body (simplified)
			String adminBody = "<h2 style='color: #d9534f;'>System Alert: Backup Failed</h2>"
					+ "<p>The automated backup process failed at <strong>" + timestamp + "</strong>.</p>"
					+ "<p><strong>Server:</strong> " + backendDomain + "</p>"
					+ "<p>The automated backup process failed at <strong>" + timestamp + "</strong>.</p>"
					+ "<p><strong>Issue:</strong> " + (e.getMessage() != null ? e.getMessage() : "Unknown error")
					+ "</p>" + "<p><strong>Cause:</strong> " + (e.getCause() != null ? e.getCause().toString() : "N/A")
					+ "</p>"
					+ "<p>Please investigate the cause immediately. If this is a recurring issue, review the backup configurations and logs.</p>"
					+ "<p style='font-size: 0.9em; color: gray;'>This message was auto-generated by the backup monitoring service.</p>";

			// Send Developer Email
			if (!developerMails.isEmpty()) {
				emailService.sendHtmlEmailAsync("Default", developerMails, List.of(), List.of(), subject, devBody);
			}

			// Send Admin Email
			if (!adminMails.isEmpty()) {
				emailService.sendHtmlEmailAsync("Default", adminMails, List.of(), List.of(), subject, adminBody);
			}

		} catch (Exception emailEx) {
			System.err.println("❌ Failed to send backup failure email: " + emailEx.getMessage());
		}
	}

	private String getStackTraceAsString(Exception e) {
		StringWriter sw = new StringWriter();
		e.printStackTrace(new PrintWriter(sw));
		return sw.toString();
	}

	private boolean shouldBackupToday(BackupScheduleConfig config, LocalDate today) {
		switch (config.getScheduleType()) {
		case DAILY:
			return true;
		case WEEKLY:
			return config.getDayOfWeek() != null
					&& today.getDayOfWeek().toString().equalsIgnoreCase(config.getDayOfWeek().toString());
		case MONTHLY:
			System.out.println("monthly");
			return config.getDayOfMonth() != null && today.getDayOfMonth() == config.getDayOfMonth();
		default:
			return false;
		}
	}
}
